{"name": "Adding New Customer into the Porta", "status": "broken", "statusDetails": {"message": "AttributeError: 'HomePage' object has no attribute 'servicesicon'", "trace": "self = <tests.test_addcustomer.Test_AddCustomer object at 0x000001E4ADA23BE0>\ngetData = {'Company Name': 'Auto_Client_0231', 'Contact Email': 'test@gmail.com', 'Contact Name': 'Test', 'Contact Number': '27623006666', ...}\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.description(\"\"\"Verifying the add customer Scenario.\"\"\")\n    @allure.story('epic_1')\n    @allure.title(\"Adding New Customer into the Porta\")\n    @allure.step\n    def test_addcust(self, getData):\n        wait = WebDriverWait(self.driver, 50)\n        log = self.getLogger()\n        actions = Actions(self.driver)\n        homePage = HomePage(self.driver)\n        #time.sleep(50)\n        wait.until(EC.visibility_of_element_located(homePage.myservices))\n        servicePage = homePage.getServicesIcon()\n>       wait.until(EC.visibility_of_element_located(homePage.servicesicon))\nE       AttributeError: 'HomePage' object has no attribute 'servicesicon'\n\ntests\\test_addcustomer.py:26: AttributeError"}, "description": "Verifying the add customer Scenario.", "steps": [{"name": "test_addcust", "status": "broken", "statusDetails": {"message": "AttributeError: 'HomePage' object has no attribute 'servicesicon'\n", "trace": "  File \"C:\\Selenium\\Selenium-Python-Framework\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"C:\\Selenium\\Selenium-Python-Framework\\tests\\test_addcustomer.py\", line 26, in test_addcust\n    wait.until(EC.visibility_of_element_located(homePage.servicesicon))\n"}, "parameters": [{"name": "getData", "value": "{'Company Name': 'Auto_Client_0231', 'UpdatedCompanyName': None, 'Credit Limit': 10, 'Contact Name': 'Test', 'Contact Number': '27623006666', 'Contact Email': 'test@gmail.com'}"}], "start": 1639669013597, "stop": 1639669019314}], "attachments": [{"name": "Screenshot", "source": "2afdda82-6948-4caf-97b1-503405827ff7-attachment.png", "type": "image/png"}, {"name": "log", "source": "85caf4ef-32a8-429d-ab74-7e7fba38ae6c-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "6ba3b0e5-8579-4b29-8097-05b0371296cd-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "getData", "value": "{'Company Name': 'Auto_Client_0231', 'UpdatedCompanyName': None, 'Credit Limit': 10, 'Contact Name': 'Test', 'Contact Number': '27623006666', 'Contact Email': 'test@gmail.com'}"}], "start": 1639669013596, "stop": 1639669019316, "uuid": "5ae1d555-eafb-4f5e-95f7-a098189ff9fa", "historyId": "33a05123a6aaf28487040ee2da07dc3b", "testCaseId": "7ad8bb180455c3005ef413273448f05b", "fullName": "tests.test_addcustomer.Test_AddCustomer#test_addcust", "labels": [{"name": "severity", "value": "critical"}, {"name": "story", "value": "epic_1"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_addcustomer"}, {"name": "subSuite", "value": "Test_AddCustomer"}, {"name": "host", "value": "ARVINDNAGPURE"}, {"name": "thread", "value": "16584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_addcustomer"}]}